"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.studentsTable = void 0;
var pg_core_1 = require("drizzle-orm/pg-core");
exports.studentsTable = (0, pg_core_1.pgTable)('students', {
    id: (0, pg_core_1.integer)().primaryKey().generatedAlwaysAsIdentity(),
    region: (0, pg_core_1.varchar)({ length: 255 }),
    center_name: (0, pg_core_1.varchar)({ length: 255 }),
    reporting_month: (0, pg_core_1.varchar)({ length: 100 }),
    unique_code: (0, pg_core_1.varchar)({ length: 50 }),
    name: (0, pg_core_1.varchar)({ length: 255 }).notNull(),
    photo: (0, pg_core_1.varchar)({ length: 255 }),
    application_form: (0, pg_core_1.varchar)({ length: 255 }),
    attendance: (0, pg_core_1.varchar)({ length: 255 }),
    placement_doc: (0, pg_core_1.varchar)({ length: 255 }),
    course: (0, pg_core_1.varchar)({ length: 100 }),
    gender: (0, pg_core_1.varchar)({ length: 100 }),
    phone: (0, pg_core_1.varchar)({ length: 100 }),
    email: (0, pg_core_1.varchar)({ length: 255 }).notNull(),
    educational_qualification: (0, pg_core_1.varchar)({ length: 100 }),
    start_date: (0, pg_core_1.varchar)({ length: 100 }),
    end_date: (0, pg_core_1.varchar)({ length: 100 }),
    placement_month: (0, pg_core_1.varchar)({ length: 100 }),
    city: (0, pg_core_1.varchar)({ length: 100 }),
    state: (0, pg_core_1.varchar)({ length: 100 }),
    address: (0, pg_core_1.text)(),
    company_name: (0, pg_core_1.varchar)({ length: 255 }),
    designation: (0, pg_core_1.varchar)({ length: 100 }),
    sector: (0, pg_core_1.text)(),
    posting_entry_level_job: (0, pg_core_1.varchar)({ length: 10 }),
    placement_county: (0, pg_core_1.varchar)({ length: 100 }),
    placement_proof: (0, pg_core_1.varchar)({ length: 255 }),
    training_proof: (0, pg_core_1.varchar)({ length: 255 }),
    training_proof_uploaded: (0, pg_core_1.varchar)({ length: 10 }),
    placement_proof_uploaded: (0, pg_core_1.varchar)({ length: 10 }),
    green_job: (0, pg_core_1.varchar)({ length: 10 }),
    household_women_headed: (0, pg_core_1.varchar)({ length: 10 }),
    pre_training_income: (0, pg_core_1.varchar)({ length: 100 }),
    post_training_income: (0, pg_core_1.varchar)({ length: 100 }),
    remarks: (0, pg_core_1.text)(),
});
